### ISSUE TITLE
Small typo causes multi-byte reads to malfunction

### ISSUE THREAD

**Issue by indraastra** [jwr/kinetis_i2c#1]
Hi there! Thanks for sharing such a lightweight, user-friendly library.

There's a small typo when disabling the ACK on the second-to-last byte of a read:

https://github.com/jwr/kinetis_i2c/blob/master/i2c.c#L171

That ~ should be deleted, which almost makes this work, except the TXAK bit has to be cleared later on, which in my code I accomplished by adding an else clause clearing it here:

https://github.com/jwr/kinetis_i2c/blob/master/i2c.c#L217

I can submit a pull request if you'd like. Let me know!

**Comment by jwr** [comment]
Wow, thanks! And thanks for the pull request, which arrived before I even had time to think about this for a moment!

At a first glance, your fix looks fine. I don't know how I could have missed this, I do use multi-byte reads regularly. I would like to think about this for a bit more, looking at the state machine model that I built — mostly to understand why I didn't notice the problem before. I think I'll be able to do this tomorrow, and I'll merge your pull request then.

One more question — did you test the code in a real setup? I don't have anything built to test it right now, so I'd like to know that it has at least been used :-)

**Comment by indraastra** [comment]
Hi Jan,

I thought that was curious, too, since you even had an example with a
multi-byte read in the docs.

I chalked the negation sign to some kind of cosmic typo that maybe happened
when you were cleaning this up and checking it in. The strange part is that
should be identical to the other block where you disable TXAK.

The second part where I clear the bit is only something you would have
noticed if you were following multi-byte reads with more operations, which
is how I even noticed it.

Our sequence looks like this:

Write register address
Read m bytes
Write register address
Read n bytes
...

Hope that helps debug the issue!

**Comment by indraastra** [comment]
Oh, and yes, we are using this code on a real kinetis k20 device. I've
monitored the communication with a logic analyzer and it seems to be
working perfectly so far. I was frankly just so relieved to be rid of the
PE driver that I didn't think to look into why I was able to trigger the
bug and you weren't.

With just the first fix removing the negation, transmission continues
perfectly until the end of the read and then a the bus gets stuck in some
bad state. This may not be a problem if a STOP immediately follows anyway
but if you have more writes in the sequence like we do, communication just
hangs. With the second line, communication continues until the whole
sequence is sent.

**Comment by jwr** [comment]
The whole reason why I wrote this code is because I looked at the PE driver and couldn't believe how bad it was.

Thank you — this looks correct, and like I said, I have no idea why I didn't notice this in my usage. Sorry for the problems and I'm glad the code works for you!
